# Generated by Django 4.1.2 on 2022-10-21 07:55

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.department'),
        ),
    ]
