# Generated by Django 4.1.2 on 2022-10-21 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='level',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='tree_id',
        ),
    ]
